name: Supabase Document Worker

on:
  schedule:
    - cron: '3,10,17,24,31,38,45,52,59 * * * *'  # every 7 minutes with offset to avoid high load
  workflow_dispatch:

jobs:
  call-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Call Async Document Processor
        run: |
          echo "Processing document generation jobs (async)..."
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            https://oeazqjeopkepqynrqsxj.supabase.co/functions/v1/async-doc-processor)
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" -ne 200 ]; then
            echo "Error: Worker function returned status $http_code"
            exit 1
          fi
          
          echo "Document submission completed successfully"
          
      - name: Check RunPod Job Status
        run: |
          echo "Checking RunPod job completion status..."
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            https://oeazqjeopkepqynrqsxj.supabase.co/functions/v1/runpod-status-checker)
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" -ne 200 ]; then
            echo "Warning: Status checker returned status $http_code (non-critical)"
          else
            echo "Status check completed successfully"
          fi 